# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paramsCv.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_paramsCv(object):
    def setupUi(self, paramsCv):
        paramsCv.setObjectName("paramsCv")
        paramsCv.resize(473, 391)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(paramsCv)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 451, 371))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:  rgb(85, 170, 127);\n"
"\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 391, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.cbb_oem = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cbb_oem.setObjectName("cbb_oem")
        self.cbb_oem.addItem("")
        self.cbb_oem.addItem("")
        self.cbb_oem.addItem("")
        self.cbb_oem.addItem("")
        self.horizontalLayout_8.addWidget(self.cbb_oem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.cbb_psm = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cbb_psm.setObjectName("cbb_psm")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.cbb_psm.addItem("")
        self.horizontalLayout_9.addWidget(self.cbb_psm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.cbb_lang = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cbb_lang.setObjectName("cbb_lang")
        self.cbb_lang.addItem("")
        self.cbb_lang.addItem("")
        self.cbb_lang.addItem("")
        self.cbb_lang.addItem("")
        self.cbb_lang.addItem("")
        self.horizontalLayout_10.addWidget(self.cbb_lang)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addWidget(self.groupBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:  rgb(85, 170, 127);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ln_kThresh = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ln_kThresh.setObjectName("ln_kThresh")
        self.horizontalLayout.addWidget(self.ln_kThresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.ln_C = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ln_C.setObjectName("ln_C")
        self.horizontalLayout_4.addWidget(self.ln_C)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ln_blockSize = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ln_blockSize.setObjectName("ln_blockSize")
        self.horizontalLayout_2.addWidget(self.ln_blockSize)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ch_useOtsu = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ch_useOtsu.setObjectName("ch_useOtsu")
        self.horizontalLayout_3.addWidget(self.ch_useOtsu)
        self.ch_normal = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ch_normal.setObjectName("ch_normal")
        self.horizontalLayout_3.addWidget(self.ch_normal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:  rgb(85, 170, 127);\n"
"\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 131, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.ln_height = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ln_height.setObjectName("ln_height")
        self.horizontalLayout_6.addWidget(self.ln_height)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.ln_width = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ln_width.setObjectName("ln_width")
        self.horizontalLayout_5.addWidget(self.ln_width)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.ln_area = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ln_area.setObjectName("ln_area")
        self.horizontalLayout_7.addWidget(self.ln_area)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:  rgb(85, 170, 127);\n"
"\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 131, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.ln_kSize = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.ln_kSize.setObjectName("ln_kSize")
        self.horizontalLayout_12.addWidget(self.ln_kSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.ln_iter = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.ln_iter.setObjectName("ln_iter")
        self.horizontalLayout_11.addWidget(self.ln_iter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)

        self.retranslateUi(paramsCv)
        QtCore.QMetaObject.connectSlotsByName(paramsCv)

    def retranslateUi(self, paramsCv):
        _translate = QtCore.QCoreApplication.translate
        paramsCv.setWindowTitle(_translate("paramsCv", "Parameter Vission"))
        self.groupBox_4.setTitle(_translate("paramsCv", "OCR"))
        self.label_18.setText(_translate("paramsCv", "oem"))
        self.cbb_oem.setItemText(0, _translate("paramsCv", "0    Legacy engine only."))
        self.cbb_oem.setItemText(1, _translate("paramsCv", "1    Neural nets LSTM engine only."))
        self.cbb_oem.setItemText(2, _translate("paramsCv", "2    Legacy + LSTM engines."))
        self.cbb_oem.setItemText(3, _translate("paramsCv", "3    Default, based on what is available."))
        self.label_19.setText(_translate("paramsCv", "psm"))
        self.cbb_psm.setItemText(0, _translate("paramsCv", "0    Orientation and script detection (OSD) only."))
        self.cbb_psm.setItemText(1, _translate("paramsCv", "1    Automatic page segmentation with OSD."))
        self.cbb_psm.setItemText(2, _translate("paramsCv", "2    Automatic page segmentation, but no OSD, or OCR."))
        self.cbb_psm.setItemText(3, _translate("paramsCv", "3    Fully automatic page segmentation, but no OSD. (Default)"))
        self.cbb_psm.setItemText(4, _translate("paramsCv", "4    Assume a single column of text of variable sizes."))
        self.cbb_psm.setItemText(5, _translate("paramsCv", "5    Assume a single uniform block of vertically aligned text."))
        self.cbb_psm.setItemText(6, _translate("paramsCv", "6    Assume a single uniform block of text."))
        self.cbb_psm.setItemText(7, _translate("paramsCv", "7    Treat the image as a single text line."))
        self.cbb_psm.setItemText(8, _translate("paramsCv", "8    Treat the image as a single word."))
        self.cbb_psm.setItemText(9, _translate("paramsCv", "9    Treat the image as a single word in a circle."))
        self.cbb_psm.setItemText(10, _translate("paramsCv", "10    Treat the image as a single character."))
        self.cbb_psm.setItemText(11, _translate("paramsCv", "11    Sparse text. Find as much text as possible in no particular order."))
        self.cbb_psm.setItemText(12, _translate("paramsCv", "12    Sparse text with OSD"))
        self.cbb_psm.setItemText(13, _translate("paramsCv", "13    Raw line. Treat the image as a single text line,bypassing hacks that are Tesseract-specific."))
        self.label_20.setText(_translate("paramsCv", "lang"))
        self.cbb_lang.setItemText(0, _translate("paramsCv", "eng"))
        self.cbb_lang.setItemText(1, _translate("paramsCv", "chi_sim"))
        self.cbb_lang.setItemText(2, _translate("paramsCv", "jpn"))
        self.cbb_lang.setItemText(3, _translate("paramsCv", "kor"))
        self.cbb_lang.setItemText(4, _translate("paramsCv", "vie"))
        self.groupBox.setTitle(_translate("paramsCv", "threshold"))
        self.label.setText(_translate("paramsCv", "k-thresh"))
        self.label_3.setText(_translate("paramsCv", "C"))
        self.label_2.setText(_translate("paramsCv", "blockSize"))
        self.ch_useOtsu.setText(_translate("paramsCv", "useOtsu"))
        self.ch_normal.setText(_translate("paramsCv", "normal"))
        self.groupBox_3.setTitle(_translate("paramsCv", "removeBlobs"))
        self.label_10.setText(_translate("paramsCv", "height"))
        self.label_7.setText(_translate("paramsCv", "width"))
        self.label_11.setText(_translate("paramsCv", "area"))
        self.groupBox_2.setTitle(_translate("paramsCv", "morphology"))
        self.label_8.setText(_translate("paramsCv", "k-size"))
        self.label_9.setText(_translate("paramsCv", "iter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    paramsCv = QtWidgets.QWidget()
    ui = Ui_paramsCv()
    ui.setupUi(paramsCv)
    paramsCv.show()
    sys.exit(app.exec_())

