# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setting(object):
    def setupUi(self, setting):
        setting.setObjectName("setting")
        setting.resize(537, 350)
        self.label = QtWidgets.QLabel(setting)
        self.label.setGeometry(QtCore.QRect(30, 10, 47, 15))
        self.label.setObjectName("label")
        self.sl_kthresh = QtWidgets.QSlider(setting)
        self.sl_kthresh.setGeometry(QtCore.QRect(80, 10, 291, 16))
        self.sl_kthresh.setMaximum(255)
        self.sl_kthresh.setOrientation(QtCore.Qt.Horizontal)
        self.sl_kthresh.setObjectName("sl_kthresh")
        self.ch_bRemoveBlobs = QtWidgets.QCheckBox(setting)
        self.ch_bRemoveBlobs.setGeometry(QtCore.QRect(80, 320, 91, 17))
        self.ch_bRemoveBlobs.setObjectName("ch_bRemoveBlobs")
        self.ch_bMorphology = QtWidgets.QCheckBox(setting)
        self.ch_bMorphology.setGeometry(QtCore.QRect(190, 320, 91, 17))
        self.ch_bMorphology.setObjectName("ch_bMorphology")
        self.gr_Morphology = QtWidgets.QGroupBox(setting)
        self.gr_Morphology.setEnabled(False)
        self.gr_Morphology.setGeometry(QtCore.QRect(260, 190, 271, 121))
        self.gr_Morphology.setObjectName("gr_Morphology")
        self.label_8 = QtWidgets.QLabel(self.gr_Morphology)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 61, 15))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.gr_Morphology)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 47, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.gr_Morphology)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_7.setObjectName("label_7")
        self.ln_iterations = QtWidgets.QLineEdit(self.gr_Morphology)
        self.ln_iterations.setGeometry(QtCore.QRect(100, 40, 70, 15))
        self.ln_iterations.setObjectName("ln_iterations")
        self.ln_ksizeMorphology = QtWidgets.QLineEdit(self.gr_Morphology)
        self.ln_ksizeMorphology.setGeometry(QtCore.QRect(100, 60, 70, 15))
        self.ln_ksizeMorphology.setObjectName("ln_ksizeMorphology")
        self.cbb_modeMorphology = QtWidgets.QComboBox(self.gr_Morphology)
        self.cbb_modeMorphology.setGeometry(QtCore.QRect(100, 20, 140, 16))
        self.cbb_modeMorphology.setObjectName("cbb_modeMorphology")
        self.gr_RemoveBlobs = QtWidgets.QGroupBox(setting)
        self.gr_RemoveBlobs.setEnabled(False)
        self.gr_RemoveBlobs.setGeometry(QtCore.QRect(260, 40, 271, 141))
        self.gr_RemoveBlobs.setObjectName("gr_RemoveBlobs")
        self.cbb_methodFindcontours = QtWidgets.QComboBox(self.gr_RemoveBlobs)
        self.cbb_methodFindcontours.setGeometry(QtCore.QRect(120, 40, 140, 16))
        self.cbb_methodFindcontours.setObjectName("cbb_methodFindcontours")
        self.label_3 = QtWidgets.QLabel(self.gr_RemoveBlobs)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 47, 15))
        self.label_3.setObjectName("label_3")
        self.ln_height = QtWidgets.QLineEdit(self.gr_RemoveBlobs)
        self.ln_height.setGeometry(QtCore.QRect(120, 80, 70, 15))
        self.ln_height.setObjectName("ln_height")
        self.label_5 = QtWidgets.QLabel(self.gr_RemoveBlobs)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 47, 15))
        self.label_5.setObjectName("label_5")
        self.ln_area = QtWidgets.QLineEdit(self.gr_RemoveBlobs)
        self.ln_area.setGeometry(QtCore.QRect(120, 100, 70, 15))
        self.ln_area.setObjectName("ln_area")
        self.label_4 = QtWidgets.QLabel(self.gr_RemoveBlobs)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 47, 15))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.gr_RemoveBlobs)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_10.setObjectName("label_10")
        self.ln_width = QtWidgets.QLineEdit(self.gr_RemoveBlobs)
        self.ln_width.setGeometry(QtCore.QRect(120, 60, 70, 15))
        self.ln_width.setObjectName("ln_width")
        self.label_9 = QtWidgets.QLabel(self.gr_RemoveBlobs)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_9.setObjectName("label_9")
        self.cbb_modeFindcontours = QtWidgets.QComboBox(self.gr_RemoveBlobs)
        self.cbb_modeFindcontours.setGeometry(QtCore.QRect(120, 20, 140, 16))
        self.cbb_modeFindcontours.setObjectName("cbb_modeFindcontours")
        self.gr_Blur = QtWidgets.QGroupBox(setting)
        self.gr_Blur.setEnabled(False)
        self.gr_Blur.setGeometry(QtCore.QRect(10, 190, 251, 121))
        self.gr_Blur.setObjectName("gr_Blur")
        self.label_11 = QtWidgets.QLabel(self.gr_Blur)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 61, 15))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.gr_Blur)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 47, 15))
        self.label_12.setObjectName("label_12")
        self.ln_ksizeBlur = QtWidgets.QLineEdit(self.gr_Blur)
        self.ln_ksizeBlur.setGeometry(QtCore.QRect(100, 40, 70, 15))
        self.ln_ksizeBlur.setObjectName("ln_ksizeBlur")
        self.cbb_modeBlur = QtWidgets.QComboBox(self.gr_Blur)
        self.cbb_modeBlur.setGeometry(QtCore.QRect(100, 20, 140, 16))
        self.cbb_modeBlur.setObjectName("cbb_modeBlur")
        self.ch_bBlur = QtWidgets.QCheckBox(setting)
        self.ch_bBlur.setGeometry(QtCore.QRect(20, 320, 91, 17))
        self.ch_bBlur.setObjectName("ch_bBlur")
        self.lb_kthresh = QtWidgets.QLabel(setting)
        self.lb_kthresh.setGeometry(QtCore.QRect(396, 5, 41, 20))
        self.lb_kthresh.setObjectName("lb_kthresh")
        self.gr_Blur_2 = QtWidgets.QGroupBox(setting)
        self.gr_Blur_2.setEnabled(True)
        self.gr_Blur_2.setGeometry(QtCore.QRect(10, 40, 251, 141))
        self.gr_Blur_2.setObjectName("gr_Blur_2")
        self.cbb_methodAdaptive = QtWidgets.QComboBox(self.gr_Blur_2)
        self.cbb_methodAdaptive.setEnabled(False)
        self.cbb_methodAdaptive.setGeometry(QtCore.QRect(100, 40, 140, 16))
        self.cbb_methodAdaptive.setObjectName("cbb_methodAdaptive")
        self.label_13 = QtWidgets.QLabel(self.gr_Blur_2)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_13.setObjectName("label_13")
        self.cbb_modeThresh = QtWidgets.QComboBox(self.gr_Blur_2)
        self.cbb_modeThresh.setGeometry(QtCore.QRect(100, 20, 140, 16))
        self.cbb_modeThresh.setObjectName("cbb_modeThresh")
        self.label_2 = QtWidgets.QLabel(self.gr_Blur_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 15))
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(self.gr_Blur_2)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 47, 15))
        self.label_14.setObjectName("label_14")
        self.ln_blockSize = QtWidgets.QLineEdit(self.gr_Blur_2)
        self.ln_blockSize.setEnabled(False)
        self.ln_blockSize.setGeometry(QtCore.QRect(100, 70, 70, 15))
        self.ln_blockSize.setObjectName("ln_blockSize")
        self.label_15 = QtWidgets.QLabel(self.gr_Blur_2)
        self.label_15.setGeometry(QtCore.QRect(20, 90, 47, 15))
        self.label_15.setObjectName("label_15")
        self.ln_C = QtWidgets.QLineEdit(self.gr_Blur_2)
        self.ln_C.setEnabled(False)
        self.ln_C.setGeometry(QtCore.QRect(100, 90, 70, 15))
        self.ln_C.setObjectName("ln_C")
        self.rad_thresh = QtWidgets.QRadioButton(setting)
        self.rad_thresh.setGeometry(QtCore.QRect(30, 150, 82, 17))
        self.rad_thresh.setChecked(True)
        self.rad_thresh.setObjectName("rad_thresh")
        self.rad_adaptive = QtWidgets.QRadioButton(setting)
        self.rad_adaptive.setGeometry(QtCore.QRect(110, 150, 82, 17))
        self.rad_adaptive.setObjectName("rad_adaptive")
        self.rad_otsu = QtWidgets.QRadioButton(setting)
        self.rad_otsu.setGeometry(QtCore.QRect(200, 150, 51, 17))
        self.rad_otsu.setObjectName("rad_otsu")
        self.but_OK = QtWidgets.QPushButton(setting)
        self.but_OK.setGeometry(QtCore.QRect(350, 320, 75, 23))
        self.but_OK.setObjectName("but_OK")
        self.but_Cancel = QtWidgets.QPushButton(setting)
        self.but_Cancel.setGeometry(QtCore.QRect(440, 320, 75, 23))
        self.but_Cancel.setObjectName("but_Cancel")

        self.retranslateUi(setting)
        QtCore.QMetaObject.connectSlotsByName(setting)

    def retranslateUi(self, setting):
        _translate = QtCore.QCoreApplication.translate
        setting.setWindowTitle(_translate("setting", "Setting"))
        self.label.setText(_translate("setting", "kthresh"))
        self.ch_bRemoveBlobs.setText(_translate("setting", "bRemoveBlobs"))
        self.ch_bMorphology.setText(_translate("setting", "bMorphology"))
        self.gr_Morphology.setTitle(_translate("setting", "morphology"))
        self.label_8.setText(_translate("setting", "modeMorpho"))
        self.label_6.setText(_translate("setting", "iterations"))
        self.label_7.setText(_translate("setting", "ksizeMorpho"))
        self.ln_iterations.setText(_translate("setting", "1"))
        self.ln_ksizeMorphology.setText(_translate("setting", "3"))
        self.gr_RemoveBlobs.setTitle(_translate("setting", "removeBlobs"))
        self.label_3.setText(_translate("setting", "width"))
        self.ln_height.setText(_translate("setting", "-1,-1"))
        self.label_5.setText(_translate("setting", "area"))
        self.ln_area.setText(_translate("setting", "-1,-1"))
        self.label_4.setText(_translate("setting", "height"))
        self.label_10.setText(_translate("setting", "methodFindcontours"))
        self.ln_width.setText(_translate("setting", "-1,-1"))
        self.label_9.setText(_translate("setting", "modeFindcontours"))
        self.gr_Blur.setTitle(_translate("setting", "blur"))
        self.label_11.setText(_translate("setting", "modeBlur"))
        self.label_12.setText(_translate("setting", "ksizeBlur"))
        self.ln_ksizeBlur.setText(_translate("setting", "3"))
        self.ch_bBlur.setText(_translate("setting", "bBlur"))
        self.lb_kthresh.setText(_translate("setting", "0"))
        self.gr_Blur_2.setTitle(_translate("setting", "thresh"))
        self.label_13.setText(_translate("setting", "methodAdaptive"))
        self.label_2.setText(_translate("setting", "modeThresh"))
        self.label_14.setText(_translate("setting", "blockSize"))
        self.ln_blockSize.setText(_translate("setting", "11"))
        self.label_15.setText(_translate("setting", "C"))
        self.ln_C.setText(_translate("setting", "3"))
        self.rad_thresh.setText(_translate("setting", "thresh"))
        self.rad_adaptive.setText(_translate("setting", "adaptive"))
        self.rad_otsu.setText(_translate("setting", "otsu"))
        self.but_OK.setText(_translate("setting", "OK"))
        self.but_Cancel.setText(_translate("setting", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setting = QtWidgets.QWidget()
    ui = Ui_setting()
    ui.setupUi(setting)
    setting.show()
    sys.exit(app.exec_())

