# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_myForm(object):
    def setupUi(self, myForm):
        myForm.setObjectName("myForm")
        myForm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(myForm)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 521, 541))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.miniWidget = QtWidgets.QWidget(self.centralwidget)
        self.miniWidget.setGeometry(QtCore.QRect(540, 10, 251, 211))
        self.miniWidget.setStyleSheet("")
        self.miniWidget.setObjectName("miniWidget")
        myForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(myForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout_2 = QtWidgets.QMenu(self.menubar)
        self.menuAbout_2.setObjectName("menuAbout_2")
        myForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(myForm)
        self.statusbar.setObjectName("statusbar")
        myForm.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(myForm)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(myForm)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(myForm)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(myForm)
        self.actionExit.setObjectName("actionExit")
        self.actionGreen = QtWidgets.QAction(myForm)
        self.actionGreen.setObjectName("actionGreen")
        self.actionBlue = QtWidgets.QAction(myForm)
        self.actionBlue.setObjectName("actionBlue")
        self.actionRed = QtWidgets.QAction(myForm)
        self.actionRed.setObjectName("actionRed")
        self.actionYellow = QtWidgets.QAction(myForm)
        self.actionYellow.setObjectName("actionYellow")
        self.action1 = QtWidgets.QAction(myForm)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(myForm)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(myForm)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(myForm)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(myForm)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(myForm)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(myForm)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(myForm)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(myForm)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(myForm)
        self.action10.setObjectName("action10")
        self.action0_1 = QtWidgets.QAction(myForm)
        self.action0_1.setObjectName("action0_1")
        self.action0_2 = QtWidgets.QAction(myForm)
        self.action0_2.setObjectName("action0_2")
        self.action0_5 = QtWidgets.QAction(myForm)
        self.action0_5.setObjectName("action0_5")
        self.action0_8 = QtWidgets.QAction(myForm)
        self.action0_8.setObjectName("action0_8")
        self.action1_2 = QtWidgets.QAction(myForm)
        self.action1_2.setObjectName("action1_2")
        self.action1_3 = QtWidgets.QAction(myForm)
        self.action1_3.setObjectName("action1_3")
        self.action1_5 = QtWidgets.QAction(myForm)
        self.action1_5.setObjectName("action1_5")
        self.action1_8 = QtWidgets.QAction(myForm)
        self.action1_8.setObjectName("action1_8")
        self.action2_2 = QtWidgets.QAction(myForm)
        self.action2_2.setObjectName("action2_2")
        self.action2_3 = QtWidgets.QAction(myForm)
        self.action2_3.setObjectName("action2_3")
        self.action2_5 = QtWidgets.QAction(myForm)
        self.action2_5.setObjectName("action2_5")
        self.action2_8 = QtWidgets.QAction(myForm)
        self.action2_8.setObjectName("action2_8")
        self.action3_2 = QtWidgets.QAction(myForm)
        self.action3_2.setObjectName("action3_2")
        self.action3_3 = QtWidgets.QAction(myForm)
        self.action3_3.setObjectName("action3_3")
        self.action3_5 = QtWidgets.QAction(myForm)
        self.action3_5.setObjectName("action3_5")
        self.action3_8 = QtWidgets.QAction(myForm)
        self.action3_8.setObjectName("action3_8")
        self.action4_2 = QtWidgets.QAction(myForm)
        self.action4_2.setObjectName("action4_2")
        self.action4_3 = QtWidgets.QAction(myForm)
        self.action4_3.setObjectName("action4_3")
        self.action4_5 = QtWidgets.QAction(myForm)
        self.action4_5.setObjectName("action4_5")
        self.action4_8 = QtWidgets.QAction(myForm)
        self.action4_8.setObjectName("action4_8")
        self.action5_2 = QtWidgets.QAction(myForm)
        self.action5_2.setObjectName("action5_2")
        self.actionColor = QtWidgets.QAction(myForm)
        self.actionColor.setObjectName("actionColor")
        self.actionFont = QtWidgets.QAction(myForm)
        self.actionFont.setObjectName("actionFont")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionColor)
        self.menuAbout.addAction(self.actionFont)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout_2.menuAction())

        self.retranslateUi(myForm)
        QtCore.QMetaObject.connectSlotsByName(myForm)

    def retranslateUi(self, myForm):
        _translate = QtCore.QCoreApplication.translate
        myForm.setWindowTitle(_translate("myForm", "MainWindow"))
        self.menuFile.setTitle(_translate("myForm", "File"))
        self.menuSetting.setTitle(_translate("myForm", "Setting"))
        self.menuAbout.setTitle(_translate("myForm", "Font"))
        self.menuHelp.setTitle(_translate("myForm", "Help"))
        self.menuAbout_2.setTitle(_translate("myForm", "About"))
        self.actionOpen.setText(_translate("myForm", "Open"))
        self.actionSave.setText(_translate("myForm", "Save"))
        self.actionSave_As.setText(_translate("myForm", "Save As"))
        self.actionExit.setText(_translate("myForm", "Exit"))
        self.actionGreen.setText(_translate("myForm", "Green"))
        self.actionBlue.setText(_translate("myForm", "Blue"))
        self.actionRed.setText(_translate("myForm", "Red"))
        self.actionYellow.setText(_translate("myForm", "Yellow"))
        self.action1.setText(_translate("myForm", "1"))
        self.action2.setText(_translate("myForm", "2"))
        self.action3.setText(_translate("myForm", "3"))
        self.action4.setText(_translate("myForm", "4"))
        self.action5.setText(_translate("myForm", "5"))
        self.action6.setText(_translate("myForm", "6"))
        self.action7.setText(_translate("myForm", "7"))
        self.action8.setText(_translate("myForm", "8"))
        self.action9.setText(_translate("myForm", "9"))
        self.action10.setText(_translate("myForm", "10"))
        self.action0_1.setText(_translate("myForm", "0.1"))
        self.action0_2.setText(_translate("myForm", "0.2"))
        self.action0_5.setText(_translate("myForm", "0.5"))
        self.action0_8.setText(_translate("myForm", "0.8"))
        self.action1_2.setText(_translate("myForm", "1"))
        self.action1_3.setText(_translate("myForm", "1.2"))
        self.action1_5.setText(_translate("myForm", "1.5"))
        self.action1_8.setText(_translate("myForm", "1.8"))
        self.action2_2.setText(_translate("myForm", "2"))
        self.action2_3.setText(_translate("myForm", "2.2"))
        self.action2_5.setText(_translate("myForm", "2.5"))
        self.action2_8.setText(_translate("myForm", "2.8"))
        self.action3_2.setText(_translate("myForm", "3"))
        self.action3_3.setText(_translate("myForm", "3.2"))
        self.action3_5.setText(_translate("myForm", "3.5"))
        self.action3_8.setText(_translate("myForm", "3.8"))
        self.action4_2.setText(_translate("myForm", "4"))
        self.action4_3.setText(_translate("myForm", "4.2"))
        self.action4_5.setText(_translate("myForm", "4.5"))
        self.action4_8.setText(_translate("myForm", "4.8"))
        self.action5_2.setText(_translate("myForm", "5"))
        self.actionColor.setText(_translate("myForm", "Color"))
        self.actionFont.setText(_translate("myForm", "Font"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myForm = QtWidgets.QMainWindow()
    ui = Ui_myForm()
    ui.setupUi(myForm)
    myForm.show()
    sys.exit(app.exec_())

