# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/result.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultDlg(object):
    def setupUi(self, ResultDlg):
        ResultDlg.setObjectName("ResultDlg")
        ResultDlg.resize(400, 519)
        font = QtGui.QFont()
        font.setPointSize(25)
        ResultDlg.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(ResultDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 380, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.but_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_start.setFont(font)
        self.but_start.setStyleSheet("color: rgb(78, 154, 6);")
        self.but_start.setObjectName("but_start")
        self.gridLayout.addWidget(self.but_start, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(78, 154, 6);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(164, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.but_stop = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_stop.setFont(font)
        self.but_stop.setStyleSheet("color: rgb(164, 0, 0);")
        self.but_stop.setObjectName("but_stop")
        self.gridLayout.addWidget(self.but_stop, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.but_reset = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_reset.setFont(font)
        self.but_reset.setStyleSheet("color: rgb(206, 92, 0);")
        self.but_reset.setObjectName("but_reset")
        self.gridLayout.addWidget(self.but_reset, 5, 2, 1, 1)
        self.lb_result = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_result.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lb_result.setFont(font)
        self.lb_result.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_result.setObjectName("lb_result")
        self.gridLayout.addWidget(self.lb_result, 3, 0, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 0, 1, 3)
        self.lb_ok = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_ok.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_ok.setFont(font)
        self.lb_ok.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_ok.setObjectName("lb_ok")
        self.gridLayout.addWidget(self.lb_ok, 0, 1, 1, 2)
        self.lb_ng = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_ng.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_ng.setFont(font)
        self.lb_ng.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_ng.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_ng.setObjectName("lb_ng")
        self.gridLayout.addWidget(self.lb_ng, 1, 1, 1, 2)
        self.lb_total = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_total.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_total.setFont(font)
        self.lb_total.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_total.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_total.setObjectName("lb_total")
        self.gridLayout.addWidget(self.lb_total, 2, 1, 1, 2)

        self.retranslateUi(ResultDlg)
        QtCore.QMetaObject.connectSlotsByName(ResultDlg)

    def retranslateUi(self, ResultDlg):
        _translate = QtCore.QCoreApplication.translate
        ResultDlg.setWindowTitle(_translate("ResultDlg", "Form"))
        self.but_start.setText(_translate("ResultDlg", "Start"))
        self.label_4.setText(_translate("ResultDlg", "<html><head/><body><p>OK</p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("ResultDlg", "NG"))
        self.but_stop.setText(_translate("ResultDlg", "Stop"))
        self.label_5.setText(_translate("ResultDlg", "Total"))
        self.but_reset.setText(_translate("ResultDlg", "Reset"))
        self.lb_result.setText(_translate("ResultDlg", "TextLabel"))
        self.lb_ok.setText(_translate("ResultDlg", "0"))
        self.lb_ng.setText(_translate("ResultDlg", "0"))
        self.lb_total.setText(_translate("ResultDlg", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultDlg = QtWidgets.QWidget()
    ui = Ui_ResultDlg()
    ui.setupUi(ResultDlg)
    ResultDlg.show()
    sys.exit(app.exec_())
